spring:

  application:
    name: demo

  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: ${USER}
    password: ${PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: ${SECRET}
  expiration: 3600000